# Generated by Django 2.2.14 on 2020-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Blood'), ('P', 'Plasma'), ('C', 'Cells')], default='B', max_length=2),
            preserve_default=False,
        ),
    ]
