# Generated by Django 2.2.14 on 2020-08-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_itemvariation_variation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variation',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemVariation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
