# Generated by Django 2.2.14 on 2020-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200820_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal')], default='s', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(default='paypal', max_length=100),
            preserve_default=False,
        ),
    ]
